name: Get Changed Files
description: Determines changed files for PR events and writes them to .tmp-changed.txt

runs:
  using: composite
  steps:
    - name: Determine changed files (PR only)
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: |
        set -euo pipefail
        git fetch origin "${{ github.base_ref }}" --depth=1
        git diff --name-only "origin/${{ github.base_ref }}"...HEAD > .tmp-changed.txt
        echo "Changed files:"
        sed 's/^/ - /' .tmp-changed.txt || true
